### ISSUE TITLE
run "make build" under "erc20-price" adds target/ under root

### ISSUE THREAD

**Issue by 0xbe1** [messari/substreams#69]
This is not expected. @Ryanmtate can you help? thanks!

**Comment by Ryanmtate** [comment]
Merging #60 will fix this. Let me rebase for review then revisit this issue if it still persists.

Under workspaces, there is a root  `target/` folder instead of crate-specific targets. The codegen build script will add a `target/` under each of the crates to store the generated code and reference locally.
